export const APP_TEXT = {
  BRAND_NAME: "Vahi Hospital OS",
  BRAND_SHORT: "VHO",
  BRAND_CONTEXT: "Hospital operating system",
  APP_DESCRIPTION: "Direct-deploy hospital operating system for invite-only staff access, OPD and IPD billing, occupancy control, communication workflows, analytics, exports, and print-safe clinical administration.",
  COMMON: {
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    SUBMIT: "Submit",
    REFRESH: "Refresh",
    LOADING: "Loading...",
    SEARCH: "Search",
    EDIT: "Edit",
    CREATE: "Create",
  },
  SHELL: {
    OVERLINE: "Hospital operating system",
    OPERATION_LABEL: "Live care operations",
    NAVIGATION_TITLE: "Operational navigation",
    NAVIGATION_DESCRIPTION: "Move across reception, billing, occupancy, communication, and governance from one shared runtime.",
    QUICK_ACTIONS: "Quick actions",
    QUICK_ACTIONS_DESCRIPTION: "Open the public site, adjust the shell, or jump to profile and settings.",
    OCCUPANCY_TITLE: "Bed pressure",
    OCCUPANCY_DESCRIPTION: "Beds occupied",
    MENU_TITLE: "Module menu",
    MENU_DESCRIPTION: "Access hospital workflows, analytics, and administrative controls.",
    PUBLIC_SITE: "Public site",
    OPEN_BOARD: "Open runtime",
    STAFF_ACCESS: "Staff access",
    OPTIONS: "Options",
    FOOTER_PRODUCT: "Vahi Hospital OS",
    FOOTER_ACCESS: "Invite-only hospital operations workspace.",
    FOOTER_NOTE: "Reception, clinical, ward, billing, and communication workflows stay connected in one system.",
    SEARCH_PLACEHOLDER: "Search patients, doctors, bills, appointments, wards, rooms, beds, or scan a barcode",
    SEARCH_IDLE: "Search patients, doctors, bills, appointments, wards, rooms, beds, or scan with hardware or camera.",
    SEARCH_TYPING: "Enter at least two characters to search.",
    SEARCH_LOADING: "Looking across permitted modules.",
    SEARCH_EMPTY: "No results in the modules you can access.",
    SEARCH_RESOLVING_BARCODE: "Resolving exact barcode match.",
    SEARCH_LIVE: "Live search",
  },
  PUBLIC: {
    NAV_LABEL: "Deployed hospital system",
    NAV_SUBTITLE: "Connected reception, billing, occupancy, communication, and governance workflows.",
    HERO_BADGE: "Direct deployment system",
    FOOTER_LABEL: "Hospital operations journal",
    FOOTER_DESCRIPTION: "Production-grade hospital operating system built for modern reception, billing, occupancy, communications, and clinical administration.",
    FOOTER_COPYRIGHT: "All rights reserved.",
  },
  FORMS: {
    CREATE_RECORD: "Create record",
    EDIT_RECORD: "Edit record",
    FORM_TITLE: "Form workspace",
    FORM_DESCRIPTION: "Use drawers for faster create and edit flows without losing context.",
    SAVE_CHANGES: "Save changes",
    CLOSE_PANEL: "Close panel",
    OPTIONS: "Options",
  },
  STATUS: {
    ONLINE: "Online",
    OFFLINE: "Offline",
    SYNCING: "Syncing",
    HEALTHY: "Sync healthy",
    QUEUED: "Queued",
    WAITING_RECONNECT: "Waiting reconnect",
    FAILED: "Failed",
  },
  PATIENTS: {
    DIRECTORY_TITLE: "Operational identity records",
    DIRECTORY_EYEBROW: "Searchable patient thread",
    REGISTER_TITLE: "Register patient",
    REGISTER_DESC: "Capture the patient identity once",
    EDIT_TITLE: "Edit patient profile",
  },
  OCCUPANCY: {
    BOARD_TITLE: "Ward occupancy and bed movement",
    BOARD_DESC: "This slice turns beds into operational records: admissions bind patients to real beds, nurses can transfer or discharge through controlled actions, and housekeeping status stays visible across wards and rooms.",
    ASSIGN_TITLE: "Assign a patient to a bed",
  },
  APPOINTMENTS: {
    ENGINE_TITLE: "Appointment scheduling and front-desk queue",
    ENGINE_DESC: "This is the first real scheduling layer from the blueprint: patient-linked bookings, active doctor lookup, queue numbers per doctor-day, and permission-controlled check-in.",
    SCHEDULE_TITLE: "Schedule appointment",
    SCHEDULE_DESC: "Bind patient, doctor, and queue position",
  },
  BILLING: {
    COMPOSER_TITLE: "Draft bill from appointment context",
    COMPOSER_DESC: "OPD billing composer",
  },
} as const;
